<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\Enums\**" />
    <EmbeddedResource Remove="Common\Enums\**" />
    <None Remove="Common\Enums\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\AnswerHistory\Commands\" />
    <Folder Include="Features\AnswerHistory\Consumers\" />
    <Folder Include="Features\AnswerHistory\Queries\" />
    <Folder Include="Features\Answer\Consumers\" />
    <Folder Include="Features\Answer\Commands\" />
    <Folder Include="Features\Answer\Queries\" />
    <Folder Include="Features\Question\Consumers\" />
    <Folder Include="Features\Question\Commands\" />
    <Folder Include="Features\Question\Queries\" />
    <Folder Include="Features\WordGuessing\GameSession\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.Abstractions" Version="8.4.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

</Project>
