services:
  engexam:
    image: pdtuan04/engexam
    container_name: engexam
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      engexam-mq:
        condition: service_healthy
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:8080
        - ConnectionStrings__EngExamConnection=Server=${DB_SERVER_RDS};Database=${DB_NAME_WRITE};User Id=${DB_USER_RDS};Password=${DB_PASS_RDS};Encrypt=True;TrustServerCertificate=True;
        - ConnectionStrings__EngExamReadDBConnection=Server=${DB_SERVER_RDS};Database=${DB_NAME_READ};User Id=${DB_USER_RDS};Password=${DB_PASS_RDS};Encrypt=True;TrustServerCertificate=True;
        - ConnectionStrings__RedisCache=${VALKEY_CONNECTION_STRING}
        - JWTKey__ValidAudience=${JWT_AUDIENCE}
        - JWTKey__ValidIssuer=${JWT_ISSUER}
        - JWTKey__Secret=${JWT_SECRET}
        - ExternalAuth__GoogleAuthOptions__ClientId=${GOOGLE_CLIENT_ID}
        - ExternalAuth__GoogleAuthOptions__ClientSecret=${GOOGLE_CLIENT_SECRET}
        - StorageOptions__StorageType=${STORAGE_TYPE}
        - StorageOptions__S3Options__Region=${S3_REGION}
        - StorageOptions__S3Options__BucketName=${S3_BUCKET_NAME}
        - StorageOptions__S3Options__CloudFrontDomain=${S3_CLOUDFRONT_DOMAIN}
        - EmailSetting__Provider=${EMAIL_PROVIDER}
        - EmailSetting__SMTPOptions__Host=${SMTP_HOST}
        - EmailSetting__SMTPOptions__Port=${SMTP_PORT}
        - EmailSetting__SMTPOptions__Username=${SMTP_USER}
        - EmailSetting__SMTPOptions__Password=${SMTP_PASS}
        - MessageBrokerSetting__Host=${MQ_HOST}
        - MessageBrokerSetting__UserName=${MQ_USER}
        - MessageBrokerSetting__Password=${MQ_PASS}
        - AIModel__ModelType=${AI_MODEL_TYPE}
    volumes:
        - images_data:/app/wwwroot/uploads/images
    networks:
      - engexam-network
    restart: always

  engexam-mq:
    image: rabbitmq:3-management
    container_name: engexam-mq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - engexam-network

  engexamui:
    image: pdtuan04/engexamui:latest
    container_name: engexamui
    restart: always
    ports:
      - "8082:8082"
    networks:
      - engexam-network
    depends_on:
      - engexam

volumes:
  images_data:
  rabbitmq_data:
networks:
  engexam-network:
    name: engexam-network
    driver: bridge